config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  get 'shopping_carts/index'
  mount Sidekiq::Web => '/jobmonitor'

  devise_for :users, as: "web"




  get  '/users/:id/profile', to: 'users#profile', as: "my_profile"
  get  '/users/:id/edit_profile', to: 'users#edit_profile', as: "edit_profile"
  get  '/users/set_current_locale', to: 'users#set_current_locale', as: "set_current_locale"


  resource :service do
    get '/index', to: "services#index"
    get '/shop', to: "services#shop"
    get '/facilities', to: "services#facilities"
    get '/individual', to: "services#individual"
    get '/appartments', to: "services#appartments"
    get '/get_time_slots', to: "services#get_time_slots"
    post '/book_appointment', to: "services#book_appointment"
  end

  root to: "services#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount_devise_token_auth_for 'User', at: '/api/v1/users', controllers: {
    registrations: 'api/v1/registrations',
    sessions: 'api/v1/sessions',
    passwords: 'api/v1/passwords',
    token_validations: 'api/v1/token_validations'
  }, skip: %i[omniauth_callbacks registrations]



  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/default_locales', to: 'api#default_locales'

      resource :user, only: %i[show update]

      devise_scope :user do
        resources :users, only: [] do
          controller :registrations do
            post :create, on: :collection
          end
        end
      end

      resource :ad do
        get '/fetch_ads', to: 'ads#ads'
      end

      resource :stores do

        get '/login_store', to: 'stores#login_store'
        post '/create_store', to: 'stores#create_store'
        get '/fetch_stores', to: 'stores#fetch_stores'
        get '/fetch_store_id', to: 'stores#fetch_store_id'
        post '/create_store_payment', to: 'stores#create_store_payment'
        post '/contact_us', to: 'stores#contact_us'
        get '/fetch_notifications', to: 'stores#fetch_notifications'
        post '/create_withdraw', to: 'stores#create_withdraw'
        get '/pending_requests', to: 'stores#pending_requests'
        get '/approved_requests', to: 'stores#approved_requests'
        put '/update_request', to: 'stores#update_request'
        get '/fetch_store_wallet', to: 'stores#fetch_store_wallet'
        get '/fetch_store_balance', to: 'stores#fetch_store_balance'
      end



      resource :cards do
        get '/fetch_cards', to: 'cards#fetch_cards'
        post '/create_gift', to: 'cards#create_gift'
        put '/claim_reward', to: 'cards#claim_reward'
        get '/fetch_transactions', to: 'cards#fetch_transactions'
        get '/fetch_rewards', to: 'cards#fetch_rewards'
        get '/fetch_claim_rewards', to: 'cards#fetch_claim_rewards'
        get '/fetch_user_wallet', to: 'cards#fetch_user_wallet'
      end


      resource :business do
        get '/show_business', to: 'businesses#show_business'
        get '/fetch_business', to: 'businesses#fetch_business'
        get '/fetch_user_list', to: 'businesses#fetch_user_list'
      end

      resource :order do
        post '/create_order', to: 'orders#create_order'
      end


    end
  end
end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id          :bigint           not null, primary key
#  attachments :text
#  description :string
#  distance    :string
#  latitude    :float
#  longitude   :float
#  ratings     :float
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#
class Service < ApplicationRecord
  mount_uploaders :attachments, AttachmentUploader
  serialize :attachments, JSON

  acts_as_taggable_on :tags
  belongs_to :user
end

app/controllers/api/v1/services_controller.rb
module Api
  module V1
    class ServicesController < Api::V1::ApiController
      helper_method :user
      skip_before_action :authenticate_user!
      #Search List


      def contact_us
        begin
          unless contact_params.present?
            return display_error('All params are not present')
          end

          if contact_params.present?
            @contact_us = Contact.new(contact_params)
            if  @contact_us.save!
              render json: {api_status: true, locale: I18n.locale.to_s,contact_us: @contact_us}
            end
          else
            render json: {api_status: false, locale: I18n.locale.to_s, error: @contact_us.errors}
          end
        rescue => e
          render json: {api_status: false, locale: I18n.locale.to_s, error: @contact_us.errors.full_messages}
        end
      end


      private

      def contact_params
        params.permit( :name, :email, :phone, :message, :user_id )
      end
        def user
        @user ||= current_user
      end

    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  require "rqrcode"
  def index

  end

  def shop
    @services = Service.all

  end

  def show
    @service = Service.find(params[:id])
  end

  def facilities
    @services = Service.all
  end

  def individual
    @services = Service.all
  end

  def appartments
    @services = Service.all
  end

  def get_time_slots
    day = params[:day]
    service = Service.find(params[:id])
    data =  render_to_string partial: "time_slot_json", locals: {day: day, service: service}
    render json: {
      data: data
    }
  end

  def book_appointment
    require "rqrcode"

    qrcode = RQRCode::QRCode.new("http://65.108.74.195:3001/")

    # NOTE: showing with default options specified explicitly
    @qr_code = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 11,
      standalone: true,
      use_path: true
    )

    @service = Service.find(params[:service_id])
    if params[:day_slot].present? && params[:time_slot].present?
       @appointment = Appointment.new
       @appointment.client_id = @service.service_provider_id
       @appointment.service_provider_id = @service.service_provider_id
       @appointment.day_slot = params[:day_slot]
       @appointment.time_slot = params[:time_slot]
       @appointment.service_id = @service.id
       if @appointment.save

       else
         redirect_to '/'
       end
    else

    end
    end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_time_slot_json.html.erb
<div class="grid-time-fx">
  <h3>Time</h3>
  <div class="grid-time">
    <%Service.time_slot(service.service_provider_id, day).each do |time| %>
    <div class="grid-time-item">
      <span><%=time %></span>
      <input type="checkbox" name="time_slot" value="<%=time %>" class="time_slot" onclick="select_time(this)">
    </div>
      <%end%>
  </div>
</div>

app/views/services/appartments.html.erb
<!DOCTYPE html>
<html lang="en">

<body>


<section class="section section__individual">

  <div class="individual__container">
    <h2 class="heading__tertiary"><%= I18n.t("appartments") %></h2>
    <div class="individual-grid">
      <%Service.tagged_with(["appartment"]).order(title: :asc).uniq.each do  |service| %>
        <a href="<%=service_path(id: service.id) %>">
        <div class="card card__author--1">
          <div class="user_detail">
            <img src="<%=service.attachments.first.url %>" alt="user image" class="user__img">
            <div class="detail">
              <span class="rating"><%=service.ratings %></span>
              <span class="mpHash">MP #3133</span>
            </div>
          </div>


          <div class="card__secondary">
            <span><%=service.title %></span>
            <span><%=service.tags.join(' | ') %></span>
          </div>
        </div>

        </a>
      <% end %>
    </div>
  </div>
</section>
<!-- Footer Section -->

</body>
</html>

app/views/services/book_appointment.html.erb
<% %>
<section class="section section__qr">
  <div class="section_qr-container">
    <h3>Done</h3>
    <div class="qr-grid">
      <div class="qr-item qr-item--1">
         <%=@qr_code.html_safe  %>
<!--        <img src="./images/qr-code.png" alt="QR code" class="qr-img">-->
        <p>Please present the qr code at your point</p>
      </div>
      <div class="qr-item qr-item--2">
        <div class="card-item">
          <span><%=@service.title %></span>
        Day:   <span><%=@appointment.day_slot %></span>
        Time:   <span><%=@appointment.time_slot %></span>
        </div>

        <div class="card__icons">
          <i class="fa fa-map-marker" aria-hidden="true"></i>
          <i class="fa fa-pencil"></i>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/services/facilities.html.erb
<!DOCTYPE html>
<html lang="en">

<body>

<!-- section Shops -->
<section class="section section__shops">
  <div class="shops__container">
    <h2 class="heading__tertiary"><%= I18n.t("facilities") %></h2>
    <div class="shops__tabs">
      <a href="#allShops" data-tab="allShops" class="b-nav-tab active"><%= I18n.t("all") %></a>
      <a href="#hospitals" data-tab="hospitals" class="b-nav-tab "><%= I18n.t("hospitals") %></a>
      <a href="#companies" data-tab="companies" class="b-nav-tab"><%= I18n.t("companies") %></a>
      <a href="#manisteries" data-tab="manisteries" class="b-nav-tab"><%= I18n.t("ministeries") %></a>


      <div id="allShops" class="b-tab active">
        <div class="grid-card-fx">
          <%Service.tagged_with(["facilities"]).order(title: :asc).uniq.each do  |service| %>
            <a href="<%=service_path(id: service.id) %>">
            <div class="card card__item-1">
            <div class="card__top">
              <img src="<%=service.attachments.first.url %>" alt="Beauty" class="card__img">
              <div class="ratings"><span class="icon_box"><i class="fa fa-star-o" aria-hidden="true"></i>
                                </span> <span class="rating-content"><%=service.ratings %></span></div>
            </div>
            <div class="card__bottom">
              <h3 class="card__title"><%=service.title %></h3>
              <p><%=service.tags.join(' | ') %></p>
            </div>
          </div>
            </a>
            <% end %>



        </div>
      </div>
    </div>


    <div id="hospitals" class="b-tab">
      <div class="grid-card-fx">
        <%Service.tagged_with(["hospital"]).order(title: :asc).uniq.each do  |service| %>
        <div class="card card__item-1">
          <div class="card__top">
            <img src="<%=service.attachments.first.url %>" alt="Beauty" class="card__img">
            <div class="ratings"><span class="icon_box"><i class="fa fa-star-o" aria-hidden="true"></i>
                                </span> <span class="rating-content"><%=service.ratings %></span></div>
          </div>
          <div class="card__bottom">
            <h3 class="card__title"><%=service.title %></h3>
            <p><%=service.tags.join(' | ') %></p>
          </div>
        </div>
          <% end %>


      </div>
    </div>


    <div id="companies" class="b-tab">
      <div class="grid-card-fx">
        <%Service.tagged_with(["company"]).order(title: :asc).uniq.each do  |service| %>
        <div class="card card__item-1">
          <div class="card__top">
            <img src="<%=service.attachments.first.url %>" alt="Beauty" class="card__img">
            <div class="ratings"><span class="icon_box"><i class="fa fa-star-o" aria-hidden="true"></i>
                                </span> <span class="rating-content"><%=service.ratings %></span></div>
          </div>
          <div class="card__bottom">
            <h3 class="card__title"><%=service.title %></h3>
            <p><%=service.tags.join(' | ') %></p>
          </div>
        </div>
          <% end %>
      </div>
    </div>


    <div id="manisteries" class="b-tab">
      <div class="grid-card-fx">
        <%Service.tagged_with(["ministry"]).order(title: :asc).uniq.each do  |service| %>
        <div class="card card__item-1">
          <div class="card__top">
            <img src="<%=service.attachments.first.url %>" alt="Beauty" class="card__img">
            <div class="ratings"><span class="icon_box"><i class="fa fa-star-o" aria-hidden="true"></i>
                                </span> <span class="rating-content"><%=service.ratings %></span></div>
          </div>
          <div class="card__bottom">
            <h3 class="card__title"><%=service.title %></h3>
            <p><%=service.tags.join(' | ') %></p>
          </div>
        </div>
          <% end %>

      </div>
    </div>
  </div>
  </div>
</section>


<!-- Footer Section -->



<script>


    function Tabs() {
        var bindAll = function() {
            var menuElements = document.querySelectorAll('[data-tab]');
            for(var i = 0; i < menuElements.length ; i++) {
                menuElements[i].addEventListener('click', change, false);
            }
        }

        var clear = function() {
            var menuElements = document.querySelectorAll('[data-tab]');
            for(var i = 0; i < menuElements.length ; i++) {
                menuElements[i].classList.remove('active');
                var id = menuElements[i].getAttribute('data-tab');
                document.getElementById(id).classList.remove('active');
            }
        }

        var change = function(e) {
            clear();
            e.target.classList.add('active');
            var id = e.currentTarget.getAttribute('data-tab');
            document.getElementById(id).classList.add('active');
        }

        bindAll();
    }

    var connectTabs = new Tabs();

</script>
</body>
</html>

app/views/services/home.html.erb
<h1>Home Page</h1>

app/views/services/index.html.erb
<!DOCTYPE html>
<html lang="en">

<body>


<!-- Header Secondary -->
<section class="section section__header--secondary">
  <div class="header__primary">
    <div class="header-box">
      <h1 class="heading-primary"><%=I18n.t("welcome_title") %></h1>
      <a href="#" class="btn btn-sign-up"><%=I18n.t("free_trial") %></a>
    </div>
  </div>
</section>

<section class="section section__recommendations">
  <div class="recommendations">
    <h2 class="heading__tertiary"><%=I18n.t("looking_for") %></h2>
    <div class="recommendation-grid">
      <a href="<%= shop_service_path %>" class="card card_item-1">
        <div class="icon__box">
          <i class="fa fa-shopping-bag" aria-hidden="true"></i>
        </div>
        <h3><%=I18n.t("shops") %></h3>
      </a>
      <a href="<%= facilities_service_path %>" class="card card_item-2">
        <div class="icon__box">
          <i class="fa fa-shopping-bag" aria-hidden="true"></i>
        </div>
        <h3><%=I18n.t("facilities") %></h3>
      </a>
      <a href="<%= individual_service_path %>" class="card card_item-3">
        <div class="icon__box">
          <i class="fa fa-shopping-bag" aria-hidden="true"></i>
        </div>
        <h3><%=I18n.t("individuals") %></h3>
      </a>
      <a href="<%= appartments_service_path %>" class="card card_item-4">
        <div class="icon__box">
          <i class="fa fa-shopping-bag" aria-hidden="true"></i>
        </div>
        <h3><%=I18n.t("appartments") %></h3>
      </a>
    </div>
  </div>
</section>
<section class="section section__appointments">
  <div class="appointments__container">
    <h2 class="heading__tertiary"><%=I18n.t("upcomming_appointments") %></h2>
    <div class="appointments">
      <div class="card card__item--1">
        <span class="card_heading">Alhabeeb Hospital</span>
        <div class="card_detail">
          <h3>Dr. Habeeb Ahmad</h3>
          <span class="date">03-03-2022</span>
        </div>
      </div>
      <div class="card card__item--2">
        <span class="card_heading">Oku</span>
        <div class="card_detail">
          <h3>Japanees restourant</h3>
          <span class="date">03-03-2022</span>
        </div>
      </div>
      <div class="card card__item--3">
        <span class="card_heading">Tuck Shop</span>
        <div class="card_detail">
          <h3>Pizza Hut</h3>
          <span class="date">03-03-2022</span>
        </div>
      </div>
      <div class="card card__item--4">
        <span class="card_heading">Auto Mobile</span>
        <div class="card_detail">
          <h3>Car auto service</h3>
          <span class="date">03-03-2022</span>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section section__recentlyAdded">
  <div class="recentAdded__container">
    <h2 class="heading__tertiary"><%=I18n.t("recently_added") %></h2>
    <div class="recent-grid-fx">
      <div class="card card-grid-fx-1">
        <img src="/images/hospital.jpg" alt="Hospital Image" class="card__img">
        <div class="card-grid-fx-detail">
          <h3>Oku</h3>
          <p>Alhabeeb Hospital</p>
        </div>
      </div>
      <div class="card card-grid-fx-2">
        <img src="/images/beauty.jpg" alt="Hospital Image" class="card__img">
        <div class="card-grid-fx-detail">
          <h3>Beauty shop</h3>
          <p>Beauty parolor</p>
        </div>
      </div>
      <div class="card card-grid-fx-3">
        <img src="/images/hospital.jpg" alt="Hospital Image" class="card__img">
        <div class="card-grid-fx-detail">
          <h3>Auto service</h3>
          <p>Car rental service</p>
        </div>
      </div>
      <div class="card card-grid-fx-4">
        <img src="/images/hospital.jpg" alt="Hospital Image" class="card__img">
        <div class="card-grid-fx-detail">
          <h3>House</h3>
          <p>Appartments</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Footer Section -->

</body>
</html>

app/views/services/individual.html.erb
<!DOCTYPE html>
<html lang="en">

<body>


<section class="section section__individual">

  <div class="individual__container">
    <h2 class="heading__tertiary"><%= I18n.t("individuals") %></h2>
    <div class="individual-grid">
      <%Service.tagged_with(["individual"]).order(title: :asc).uniq.each do  |service| %>
        <a href="<%=service_path(id: service.id) %>">
      <div class="card card__author--1">
        <div class="user_detail">
          <img src="<%=service.attachments.first.url %>" alt="user image" class="user__img">
          <div class="detail">
            <span class="rating"><%=service.ratings %></span>
            <span class="mpHash">MP #3133</span>
          </div>
        </div>


        <div class="card__secondary">
          <span><%=service.title %></span>
          <span><%=service.tags.join(' | ') %></span>
        </div>
      </div>
        </a>
    <% end %>
    </div>
  </div>
</section>
<!-- Footer Section -->

</body>
</html>

app/views/services/shop.html.erb
<!DOCTYPE html>
<html lang="en">

<body>


<!-- section Shops -->
<section class="section section__shops">
  <div class="shops__container">
    <h2 class="heading__tertiary"><%= I18n.t("our_shops") %></h2>
    <div class="shops__tabs">

      <a href="#allShops" data-tab="allShops" class="b-nav-tab active"><%= I18n.t("all") %></a>
      <a href="#restourants" data-tab="restourants" class="b-nav-tab "><%= I18n.t("resturants") %></a>
      <a href="#barbers" data-tab="barbers" class="b-nav-tab"><%= I18n.t("barbers") %></a>
      <a href="#beautySaloons" data-tab="beautySaloons" class="b-nav-tab"><%= I18n.t("beauty_saloons") %></a>


      <div id="allShops" class="b-tab active">
        <div class="grid-card-fx">
          <%Service.tagged_with(["shop"]).uniq.each do  |service| %>
           <a href="<%=service_path(id: service.id) %>">
            <div class="card card__item-1">
              <div class="card__top">
                <img src="<%=service.attachments.first.url %>" alt="Beauty" class="card__img" style='width: 100%; height: 100%'>
                <div class="ratings"><span class="icon_box"><i class="fa fa-star-o" aria-hidden="true"></i>
                                </span> <span class="rating-content"><%=service.ratings %></span></div>
              </div>
              <div class="card__bottom">
                <h3 class="card__title"><%=service.title %></h3>
                <p><%=service.tags.join(' | ') %></p>
              </div>
            </div>
           </a>
            <%end %>
        </div>
      </div>

      <div id="restourants" class="b-tab">
        <div class="grid-card-fx">

          <%Service.tagged_with(["restaurants"]).order(title: :asc).uniq.each do  |service| %>
            <a href="<%=service_path(id: service.id) %>">
            <div class="card card__item-1">
            <div class="card__top">
              <img src="<%=service.attachments.first.url %>" alt="Beauty" class="card__img">
              <div class="ratings"><span class="icon_box"><i class="fa fa-star-o" aria-hidden="true"></i>
                                </span> <span class="rating-content"><%=service.ratings %></span></div>
            </div>
            <div class="card__bottom">
              <h3 class="card__title"><%= service.title %></h3>
              <p><%=service.tags.join(' | ') %></p>
            </div>
          </div>
            </a>
            <%end %>

        </div>
      </div>

      <div id="barbers" class="b-tab">
        <div class="grid-card-fx">
          <%Service.tagged_with(["barber"]).order(title: :asc).uniq.each do  |service| %>
            <a href="<%=service_path(id: service.id) %>">
          <div class="card card__item-1">
            <div class="card__top">
              <img src="<%=service.attachments.first.url %>" alt="Beauty" class="card__img">
              <div class="ratings"><span class="icon_box"><i class="fa fa-star-o" aria-hidden="true"></i>
                                </span> <span class="rating-content"><%=service.ratings %></span></div>
            </div>
            <div class="card__bottom">
              <h3 class="card__title"><%= service.title %></h3>
              <p><%=service.tags.join(' | ') %></p>
            </div>
          </div>
            </a>
            <% end %>

        </div>
      </div>
      <div id="beautySaloons" class="b-tab">
        <div class="grid-card-fx">
          <%Service.tagged_with(["beauty"]).order(title: :asc).uniq.each do  |service| %>
            <a href="<%=service_path(id: service.id) %>">
          <div class="card card__item-1">
            <div class="card__top">
              <img src="<%=service.attachments.first.url %>" alt="Beauty" class="card__img">
              <div class="ratings"><span class="icon_box"><i class="fa fa-star-o" aria-hidden="true"></i>
                                </span> <span class="rating-content"><%=service.ratings %></span></div>
            </div>
            <div class="card__bottom">
              <h3 class="card__title"><%= service.title %></h3>
              <p><%=service.tags.join(' | ') %></p>
            </div>
          </div>
            </a>
            <% end %>

        </div>
      </div>
    </div>
  </div>
</section>


<!-- Footer Section -->



<script>


    function Tabs() {
        var bindAll = function() {
            var menuElements = document.querySelectorAll('[data-tab]');
            for(var i = 0; i < menuElements.length ; i++) {
                menuElements[i].addEventListener('click', change, false);
            }
        }

        var clear = function() {
            var menuElements = document.querySelectorAll('[data-tab]');
            for(var i = 0; i < menuElements.length ; i++) {
                menuElements[i].classList.remove('active');
                var id = menuElements[i].getAttribute('data-tab');
                document.getElementById(id).classList.remove('active');
            }
        }

        var change = function(e) {
            clear();
            e.target.classList.add('active');
            var id = e.currentTarget.getAttribute('data-tab');
            document.getElementById(id).classList.add('active');
        }

        bindAll();
    }

    var connectTabs = new Tabs();

</script>
</body>
</html>

app/views/services/show.html.erb
<section class="section section-book">
  <div class="book-appointment">
    <div class="book-appointment-grid-fx">
      <div class="grid-item grid-item-1">
        <img src="<%= @service.attachments.first.url %>" alt="hospital Image" class="grid-image">
        <div class="detail">
          <h3><%= @service.title %></h3>
          <h4>Owner:<%= @service.service_provider.first_name.capitalize %></h4>
        </div>
      </div>

      <div class="select__group">
        <h3>Description: <%= @service.description %></h3>
      </div>
    </div>
    <form action="/service/book_appointment" method="post">
      <div class="grid-date-time-fx">
        <h3>Dates:</h3>
        <div class="grid-date-time-container">

          <% Service.available_days(@service.service_provider_id).each do |slot| %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
            <%= hidden_field_tag :service_id, @service.id -%>


            <div class="grid-item ">
              <span><%= slot %></span>
              <input type="checkbox" name="day_slot" value="<%= slot %>" class="day_slot" onclick="select_day(this)">
            </div>
          <% end %>
        </div>
      </div>
      <div id="time_slots_box">
        <h4 style="text-align: center">Please choose day first!</h4>
      </div>


      <div class="button--grid">
        <button type="submit" class="btn-grid-btn">Submit</button>
      </div>
    </form>
  </div>
</section>
<script>
    function select_time(c) {
        console.log("select_day")
        $(".time_slot").prop("checked", false)
        $(this).prop("checked", true)
        $(c).prop("checked", true)
    }
    function select_day(c) {
        console.log("select_day")
        $(".day_slot").prop("checked", false)
        $(this).prop("checked", true)
        $(c).prop("checked", true)
        var day = $(c).val();
        // http://localhost:3000//service/get_time_slots
        $.ajax({
            type: "GET",
            url: "/service/get_time_slots",
            data: {day: day, id: '<%=@service.id %>' },
            cache: false,
            success: function(data){
                console.log("appending slots")
                $("#time_slots_box").html(data.data)
                // alert(data.data)
            },
            error: function(data){
                window.location.href = '/users/sign_in'
            }
        });
    }
</script>