config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do


  get 'shopping_carts/index'
  mount Sidekiq::Web => '/jobmonitor'

  devise_for :users, as: "web"




  get  '/users/:id/profile', to: 'users#profile', as: "my_profile"
  get  '/users/:id/edit_profile', to: 'users#edit_profile', as: "edit_profile"
  get  '/users/set_current_locale', to: 'users#set_current_locale', as: "set_current_locale"


  resource :service do
    get '/index', to: "services#index"
    get '/shop', to: "services#shop"
    get '/facilities', to: "services#facilities"
    get '/individual', to: "services#individual"
    get '/appartments', to: "services#appartments"
    get '/get_time_slots', to: "services#get_time_slots"
    post '/book_appointment', to: "services#book_appointment"
  end

  root to: "services#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  mount_devise_token_auth_for 'User', at: '/api/v1/users', controllers: {
    registrations: 'api/v1/registrations',
    sessions: 'api/v1/sessions',
    passwords: 'api/v1/passwords',
    token_validations: 'api/v1/token_validations'
  }, skip: %i[omniauth_callbacks registrations]



  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/default_locales', to: 'api#default_locales'

      resource :user, only: %i[show update]

      devise_scope :user do
        resources :users, only: [] do
          controller :registrations do
            post :create, on: :collection
          end
        end
      end

      resource :ad do
        get '/fetch_ads', to: 'ads#ads'
      end

      resource :stores do

        get '/login_store', to: 'stores#login_store'
        post '/create_store', to: 'stores#create_store'
        get '/fetch_stores', to: 'stores#fetch_stores'
        get '/fetch_store_id', to: 'stores#fetch_store_id'
        post '/create_store_payment', to: 'stores#create_store_payment'
        post '/contact_us', to: 'stores#contact_us'
        get '/fetch_notifications', to: 'stores#fetch_notifications'
        post '/create_withdraw', to: 'stores#create_withdraw'
        get '/pending_requests', to: 'stores#pending_requests'
        get '/approved_requests', to: 'stores#approved_requests'
        put '/update_request', to: 'stores#update_request'
        get '/fetch_store_wallet', to: 'stores#fetch_store_wallet'
        get '/fetch_store_balance', to: 'stores#fetch_store_balance'
      end



      resource :cards do
        get '/fetch_cards', to: 'cards#fetch_cards'
        post '/create_gift', to: 'cards#create_gift'
        put '/claim_reward', to: 'cards#claim_reward'
        get '/fetch_transactions', to: 'cards#fetch_transactions'
        get '/fetch_rewards', to: 'cards#fetch_rewards'
        get '/fetch_claim_rewards', to: 'cards#fetch_claim_rewards'
        get '/fetch_user_wallet', to: 'cards#fetch_user_wallet'
      end


      resource :business do
        get '/show_business', to: 'businesses#show_business'
        get '/fetch_business', to: 'businesses#fetch_business'
        get '/fetch_user_list', to: 'businesses#fetch_user_list'
      end

      resource :order do
        post '/create_order', to: 'orders#create_order'
      end


    end
  end
end

app/views/layouts/_footer.html.erb
<!-- Footer Section -->
<footer class="footer">
  <div class="footer__addr">
    <h1 class="footer__logo"><%=I18n.t("my_appointment") %></h1>

    <h2>Contact</h2>

    <address>
      North America, FL street 229 EB<br>

      <!-- <a class="footer__btn" href="mailto:example@gmail.com">Email Us</a> -->
    </address>
  </div>

  <ul class="footer__nav">
    <li class="nav__item">
      <h2 class="nav__title">Categories</h2>

      <ul class="nav__ul">
        <li>
          <a href="#">Shops</a>
        </li>

        <li>
          <a href="#">Hospitals</a>
        </li>

        <li>
          <a href="#">Beauty shops</a>
        </li>
      </ul>
    </li>

    <li class="nav__item nav__item--extra">
      <h2 class="nav__title">Quick Links</h2>

      <ul class="nav__ul nav__ul--extra">
        <li>
          <a href="#">Home</a>
        </li>

        <li>
          <a href="#">About</a>
        </li>

        <li>
          <a href="#">Services</a>
        </li>

        <li>
          <a href="#">Contact</a>
        </li>

        <li>
          <a href="#">Sell online</a>
        </li>

        <li>
          <a href="#">IoT</a>
        </li>
      </ul>
    </li>

    <li class="nav__item">
      <h2 class="nav__title">Rights & Rules</h2>

      <ul class="nav__ul">
        <li>
          <a href="#">Privacy Policy</a>
        </li>

        <li>
          <a href="#">Terms of Use</a>
        </li>

        <li>
          <a href="#">Sitemap</a>
        </li>
      </ul>
    </li>
  </ul>

  <div class="legal">
    <p>&copy; 2019 Something. All rights reserved.</p>

    <!-- <div class="legal__links">
      <span>Appointment builders |  Available everytime and everywhere</span>
    </div> -->
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <span class="logo"><%= I18n.t("my_appointment") %></span>

  <ul class="menu">
    <li class="list__item"><%= link_to "#{I18n.t("home")}", root_path %></li>
    <li class="list__item"><%= link_to "#{I18n.t("shops")}", shop_service_path %></li>
    <li class="list__item"><%= link_to "#{I18n.t("facilities")}", facilities_service_path %></li>
    <li class="list__item"><%= link_to "#{I18n.t("chat")}" %></li>
    <li class="list__item"><%= link_to "#{I18n.t("profile")}" %></li>
    <% if session[:locale].nil? %>
      <%=link_to "AR", set_current_locale_path(locale: "ar"), remote: true, style: "font-size: 18px;" %>
    <%elsif  session[:locale] == "en" %>
      <%=link_to "AR", set_current_locale_path(locale: "ar"), remote: true, style: "font-size: 18px;" %>
    <%else%>
      <%=link_to "EN", set_current_locale_path(locale: "en"), remote: true ,style: "font-size: 18px;" %>
    <%end%>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGift</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="./css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>



  <%= render partial: "layouts/header" %>
  <%= yield %>
<!--  <img src="/public/logo.png" alt="logo" width="500" height="600">-->
  <%= render partial: "layouts/footer" %>
  </body>
  </html>